-- MySQL Script generated by MySQL Workbench
-- Sat Jul  2 01:16:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema listadotrabajadores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema listadotrabajadores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listadotrabajadores` DEFAULT CHARACTER SET utf8 ;
USE `listadotrabajadores` ;

-- -----------------------------------------------------
-- Table `listadotrabajadores`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`areas` (
  `id_areas` INT(11) NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_areas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `listadotrabajadores`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`trabajador` (
  `rut` VARCHAR(15) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `listadotrabajadores`.`cargas_familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`cargas_familiares` (
  `rut_fam` VARCHAR(15) NOT NULL,
  `nombre_carga_familiar` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `trabajador_rut` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`rut_fam`, `trabajador_rut`),
  CONSTRAINT `fk_cargas_familiares_trabajador1`
    FOREIGN KEY (`trabajador_rut`)
    REFERENCES `listadotrabajadores`.`trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `listadotrabajadores`.`contactos_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`contactos_emergencia` (
  `id_emergencia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `relacion_trabajador` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `trabajador_rut` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_emergencia`, `trabajador_rut`),
  CONSTRAINT `fk_contactos_emergencia_trabajador1`
    FOREIGN KEY (`trabajador_rut`)
    REFERENCES `listadotrabajadores`.`trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `listadotrabajadores`.`datos_laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`datos_laborales` (
  `id_datos_laborales` INT(11) NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `areas_id_areas` INT(11) NOT NULL,
  PRIMARY KEY (`id_datos_laborales`, `areas_id_areas`),
  CONSTRAINT `fk_datos_laborales_areas1`
    FOREIGN KEY (`areas_id_areas`)
    REFERENCES `listadotrabajadores`.`areas` (`id_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `listadotrabajadores`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`departamentos` (
  `id_departamentos` INT(11) NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamentos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `listadotrabajadores`.`ficha_trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listadotrabajadores`.`ficha_trabajador` (
  `num_ficha` INT(11) NOT NULL AUTO_INCREMENT,
  `departamentos_id_departamentos` INT(11) NOT NULL,
  `datos_laborales_id_datos_laborales` INT(11) NOT NULL,
  `trabajador_rut` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`num_ficha`),
  CONSTRAINT `fk_ficha_trabajador_datos_laborales1`
    FOREIGN KEY (`datos_laborales_id_datos_laborales`)
    REFERENCES `listadotrabajadores`.`datos_laborales` (`id_datos_laborales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_trabajador_departamentos1`
    FOREIGN KEY (`departamentos_id_departamentos`)
    REFERENCES `listadotrabajadores`.`departamentos` (`id_departamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_trabajador_trabajador1`
    FOREIGN KEY (`trabajador_rut`)
    REFERENCES `listadotrabajadores`.`trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO areas (area) VALUES ("admin");
INSERT INTO departamentos(departamento) VALUES ("admin");
INSERT INTO trabajador VALUES ("admin","admin","admin","admin","admin","admin","admin","admin123");
INSERT INTO datos_laborales (cargo, fecha_ingreso, areas_id_areas) VALUES ("Administrador", SYSDATE(), 1);
INSERT INTO ficha_trabajador(departamentos_id_departamentos, datos_laborales_id_datos_laborales, trabajador_rut) VALUES (1, 1, "admin");

